"""Build the veRL training and validation parquet for the tau2 telecom arms.

    /root/autodl-tmp/envs/verl/bin/python scripts/build_rl_data.py --out data/rl

One row is one task, not one trajectory: veRL samples G rollouts per row itself. The row
carries the prompt the policy will start from and, in `extra_info.task_id`, the handle the
agent loop needs to construct that task's episode.

The prompt is built the same way the SFT data was -- `SYSTEM_PROMPT` formatted with the live
domain policy and agent instruction -- because a rollout that starts from a different system
message than training did is measuring a different model. The first customer message is
deliberately absent: it is generated by the user simulator at reset, so it belongs to the
episode rather than to the dataset.

The training pool is `full \ base`. The 114 `base` tasks are the frozen evaluation set and
never enter training; holding them out is the only reason arm-to-arm comparisons mean
anything. Validation during training is drawn from the training pool for the same reason.
"""

from __future__ import annotations

import argparse
import json
import os
import random


def domain_context(domain: str) -> str:
    from tau2.agent.llm_agent import AGENT_INSTRUCTION, SYSTEM_PROMPT
    from tau2.registry import registry

    env = registry.get_env_constructor(domain)(solo_mode=False)
    return SYSTEM_PROMPT.format(domain_policy=env.get_policy(), agent_instruction=AGENT_INSTRUCTION)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--domain", default="telecom")
    ap.add_argument("--out", default="data/rl")
    ap.add_argument("--n-val", type=int, default=64, help="tasks held out of training, from the pool")
    ap.add_argument("--seed", type=int, default=0)
    args = ap.parse_args()

    import pandas as pd

    root = f"/root/autodl-tmp/tau2-bench/data/tau2/domains/{args.domain}"
    splits = json.load(open(f"{root}/split_tasks.json"))
    pool = sorted(set(splits["full"]) - set(splits["base"]))
    print(f"full {len(splits['full'])}, base {len(splits['base'])} held out, pool {len(pool)}")

    system_prompt = domain_context(args.domain)
    print(f"system prompt: {len(system_prompt)} chars")

    rng = random.Random(args.seed)
    shuffled = pool[:]
    rng.shuffle(shuffled)
    val_ids, train_ids = set(shuffled[: args.n_val]), shuffled[args.n_val :]

    def rows(ids, split):
        out = []
        for i, task_id in enumerate(sorted(ids)):
            out.append({
                "data_source": f"tau2_{args.domain}",
                "prompt": [{"role": "system", "content": system_prompt}],
                "agent_name": "tau2",
                "ability": "tool_use",
                "reward_model": {"style": "rule", "ground_truth": task_id},
                "extra_info": {"index": i, "split": split, "task_id": task_id,
                               "need_tools_kwargs": False},
            })
        return out

    os.makedirs(args.out, exist_ok=True)
    for name, ids in (("train", train_ids), ("val", val_ids)):
        df = pd.DataFrame(rows(ids, name))
        path = os.path.join(args.out, f"{name}.parquet")
        df.to_parquet(path)
        print(f"wrote {path}: {len(df)} tasks")

    leak = set(val_ids) & set(train_ids)
    assert not leak, f"validation leaks into training: {leak}"
    assert not (set(pool) & set(splits["base"])), "the evaluation set leaked into the pool"
    print("no overlap between train, val and the frozen base set")


if __name__ == "__main__":
    main()
